### ISSUE TITLE
Cannot compile GECKO

### ISSUE THREAD

**Issue by David-Estevez** [David-Estevez/gecko#1]
Apart from missing installation instructions, I get some errors when compiling GECKO on a new computer.

**Comment by David-Estevez** [comment]
I have tried to compile it with @JuanFdelArco today, and the main errors were:

* ColorDebug has to be downloaded, maybe we should use [superbuild](https://github.com/roboticslab-uc3m/QA/issues/1) instead of git submodules.
* Haar cascades template file is hardcoded, resulting in errors when the location of the file changes (due to differences in the OpenCV installation). This does not cause a compilation error, but a runtime error.

**Comment by crearo** [comment]
I cloned ColorDebug and put the source in external/ folder. I then tried to build and this is the following error : 

```
In file included from gecko/src/libraries/handUtils.h:33:0,
                 from gecko/src/libraries/handUtils.cpp:27:
gecko/src/libraries/backgroundSubstractor.h: In member function ‘void backgroundSubstractor::setbackgroundRatio(float)’:
gecko/src/libraries/backgroundSubstractor.h:37:38: error: ‘backgroundRatio’ was not declared in this scope
     void setbackgroundRatio(float a){backgroundRatio = a;}
                                      ^
gecko/src/libraries/handUtils.cpp: In function ‘void backgroundSubs(cv::Mat&, backgroundSubstractor&)’:
gecko/src/libraries/handUtils.cpp:177:18: error: no match for call to ‘(backgroundSubstractor) (cv::Mat&, cv::Mat&)’
     bg(frame,fore);
                  ^
src/libraries/CMakeFiles/HandUtils.dir/build.make:62: recipe for target 'src/libraries/CMakeFiles/HandUtils.dir/handUtils.cpp.o' failed
make[2]: *** [src/libraries/CMakeFiles/HandUtils.dir/handUtils.cpp.o] Error 1
CMakeFiles/Makefile2:283: recipe for target 'src/libraries/CMakeFiles/HandUtils.dir/all' failed
make[1]: *** [src/libraries/CMakeFiles/HandUtils.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Could this be because I am using OpenCV 3.2? Would really love to try out/contribute to Gecko!

**Comment by David-Estevez** [comment]
Hi @CreaRo !

I've been taking a look to the [docs for OpenCV 3.2](http://docs.opencv.org/3.2.0/d1/dc5/tutorial_background_subtraction.html) and it seems that the related API for the background subtractor we use in Gecko has changed. In summary, the background subtractor creation is now done differenty, and our approach is no longer valid, so Gecko doesn't not work with OpenCV 3.2.

Is there any reason to use OpenCV 3.2? Could you try with the older 2.x version?

**Comment by crearo** [comment]
The reason I use OpenCV 3.2 is because of the Java wrappers that come with it. No worries though, I shall download 2.4.13 version and try to compile once again! I'll post here once I do.

Edit : Compiled successfully!
